services:
  controller:
    build: .
    environment:
      - RUST_LOG=debug
    volumes:
      - type: bind
        source: config.toml
        target: /app/config.toml
      - type: bind
        source: $HOME/.config/openstack
        target: /etc/openstack
