version: "3"

services:
  controller:
    build: .
    volumes:
      - type: bind
        source: config.yml
        target: /app/config.yml
      - type: bind
        source: $HOME/.config/openstack
        target: /etc/openstack
